### ISSUE TITLE
Hide back layout when front layout is touched

### ISSUE THREAD

**Issue by Marcosmaliki** [roiacult/BackdropLayout#3]
Awesome library as we wait for the official material version. I can't however hide the back layout by touching the top layout. Is this possible?

**Comment by Marcosmaliki** [comment]
`   private fun update(withAnimation : Boolean) {
        when(state) {
            State.OPEN -> {
                getToolbar()?.setNavigationIcon(closeIcon)
                val transitionHeight = getTransitionHeight()
                if(withAnimation) startTranslateAnimation(transitionHeight)
                else getFrontLayout().translationY = transitionHeight
            }

            State.CLOSE -> {
                getToolbar()?.setNavigationIcon(menuIcon)
                if(withAnimation) startTranslateAnimation(0F)
                else getFrontLayout().translationY = 0F
            }
        }
    }`

This is exactly the function I need access to

**Comment by roiacult** [comment]
fun open()
fun close()
or u can use : fun switch() to change backdropLayout state 
all this function are public you can use them
so inorder to close backdropLatout when touching the front layout u can do this
`yourFrontLayout.setOnClickListener{
     backdropLayout.close()
}`
