### ISSUE TITLE
Reverse height

### ISSUE THREAD

**Issue by paswd** [roiacult/BackdropLayout#4]
Hello! I have a problem with method

`private fun getTransitionHeight(): Float {`
`return Math.min(getBackLayout().height.toFloat(),height - peeckHeight)`
`}`

So, for correct work user must insert in peeckHeight height of front layout. But if I want to dropdown depending of background content height I need to insert height to global top like here:

`return Math.min(getBackLayout().height.toFloat(),peeckHeight)`

I think it will be better if you do a parameter to make it optional. Thanks.

**Comment by roiacult** [comment]
peeckHeight is not the height of front layout is the height of the header of front layout it means when we droopdown we  need to keep thats header of front layout visible 
translation should be "height - peeckHeight"
so i m not sure why u want it like this 
`return Math.min(getBackLayout().height.toFloat(),peeckHeight)`

**Comment by paswd** [comment]
Oh, I understood the idea of this element, thanks. But I have a non-standart task - make a short menu in background layer. Several elements ang very big empty space - I think it is not beautiful. So, a variant - pull back the height of background layer menu and make foreground layer disabled. But I will tell your opinion to our designer.

**Comment by roiacult** [comment]
maybe because ur setting the height of backlayout to "match_parent" 
if its the case you should change it to "wrap_content" and i think this will solve the problem of the big empty space
and about disabling the front layout i will work on it and i will informe you about any updates

**Comment by paswd** [comment]
Yes, I've already done this. But also I changed `height - peeckHeight` to `height` with `peeckHeight` value is background menu's height. And it works as I want. The problem cannot be solved only with changing "match_parent" to "wrap_content".

Okay, I will wait for your updates, thanks a lot. And my opinion: your version of Backdrop is the best between all I found today.

**Comment by roiacult** [comment]
you can now use version v2.0
frontlayout will be disabled when backdroplayout is in open state
